"""
Typed state for the LangGraph self-reflective RAG agent.

The graph is a CRAG / Self-RAG style loop:

    classify -> retrieve -> rerank -> grade_docs
        -> transform_query (retry)   if docs are insufficient
        -> generate -> verify        if docs are sufficient
    verify -> END   if the answer is grounded
    verify -> refuse (END)  if the answer is fabricated / ungrounded

``Annotated[list, add_or_replace]`` reducers let successive retrieval rounds
*accumulate* documents instead of clobbering them, which is what makes the
retry-rewrite loop actually improve recall rather than restart from scratch.
"""

from __future__ import annotations

from typing import Annotated, Any, Dict, List, Optional, TypedDict

from langchain_core.documents import Document


def add_or_replace(left: List[Document], right: Optional[List[Document]]) -> List[Document]:
    """Reducer: merge document lists, de-duplicating by (source, page, content hash).

    A retry round adds newly retrieved docs without dropping earlier good ones.
    """
    if right is None:
        return left or []
    merged: List[Document] = list(left or [])
    seen = set()
    for d in merged:
        seen.add(_doc_key(d))
    for d in right:
        k = _doc_key(d)
        if k not in seen:
            merged.append(d)
            seen.add(k)
    return merged


def _doc_key(d: Document) -> str:
    src = d.metadata.get("source", "")
    page = d.metadata.get("page", "")
    # First 120 chars are enough to de-dup near-identical chunks.
    return f"{src}|{page}|{d.page_content[:120]}"


class AgentState(TypedDict, total=False):
    """Mutable state flowing through every node of the LangGraph agent.

    Each node receives the full state and returns a *partial* dict that is
    merged back in (LangGraph applies the field reducers).
    """

    # The user's original question (never mutated).
    question: str

    # Conversation history block (multiline string) for multiturn chat.
    # Empty when running single-turn. The generate node prepends it to context
    # so the model can phrase answers naturally and reference earlier turns.
    history: str

    # Output tone: "technical" (university-level) or "intuitive" (hobbyist).
    # Selects which prompt the generate node uses. Same grounding either way.
    tone: str

    # The router's decision: "retrieve" (in-domain, needs the corpus) or
    # "refuse" (off-topic / out of scope).
    route: str

    # Query variants generated by the rewriter (sub-queries + a HyDE answer).
    # Drives a richer hybrid retrieval.
    rewritten_queries: List[str]

    # Retrieved chunks accumulate across retry rounds via add_or_replace.
    documents: Annotated[List[Document], add_or_replace]

    # Relevance grades (1 = relevant, 0 = not) aligned 1:1 with `documents`
    # *after* the final retrieval round (post-rerank).
    doc_grades: List[int]

    # How many retrieval rounds have run (bounds the retry loop).
    retrieval_rounds: int

    # Final generated answer.
    answer: str

    # Claim-level faithfulness result from the verifier node.
    verification: Dict[str, Any]

    # Final decision flag.
    refused: bool

    # Free-text reason for a refusal / retry (for eval artifacts).
    reason: str

    # Wall-clock trace per node, for latency analysis.
    trace: Dict[str, float]
